### ISSUE TITLE
Feature request shuffle play

### ISSUE THREAD

**Issue by theopenbit** [souch/SMP#10]
Hi souch,
thanks for this tiny music player. It's the main music player on my device for local music. Nevertheless I miss the possibility of shuffle play : -(
Will it be available in future?

Thanks,
theOpenBit

**Comment by souch** [comment]
Hi, it is already in the todo list. I will try to put it in the next release. It seems easy to implement.

Thanks.

**Comment by theopenbit** [comment]
Great! Thanks!

**Comment by souch** [comment]
Your welcome. I did not want to bloat the item menu so the shuffle func is enable/disable through the settings, I hope it is not too cumbersome.

**Comment by theopenbit** [comment]
It's working like expected. Many Thanks! It isn't to  cumbersome. I like the music player because of its simple ui. Configuring shuffle via the settings is all right

**Comment by souch** [comment]
Thanks for the feedback.
