### ISSUE TITLE
Feature Request: Simple Last.FM Scrobbler Integration

### ISSUE THREAD

**Issue by edo9k** [souch/SMP#11]
SMP has become my main music player, I really appretiate the minimalist interface.
But it does not get recognized by the Simple Last.FM and Libre.FM scrobbler, it would be great if it did. Please consider this feature when you have some time.

Thank you a lot, it's a great player.

**Comment by souch** [comment]
Thanks,

I never used Last.FM and Libre.FM. I will try someday. For me sicmu player advantage is the big list view with foldable group. And from what I understand, I do not see what would Last.FM playlist benefit from sicmu's specific view. 

I perhaps need to try it to understand. But I need first to implement the recursive folder view (#6).

**Comment by souch** [comment]
Hi again,
I understood what you meant. It is not complex, I'll try to do it for the next release.
