### ISSUE TITLE
Feature Request: color configuration

### ISSUE THREAD

**Issue by goldencut** [souch/SMP#12]
or 'theming' - fonts, UI elements, background...

**Comment by souch** [comment]
yes why not, I'll have a look someday. Everybody do not like black and red perhaps.

**Comment by goldencut** [comment]
I quite like the current color schema, it's different, the settings icon
fits it nicely too. But all things get boring over time, and sometimes the
mood (music) also requires something else..
If I could change something else I'd make play-pause button bigger (wider),
that's the button most used. Maybe put it in the middle?
|goto|prev|PLAY|next|lock|
About audiobooks - it would be a nice addition if the player could remember
the last location (time) in addition to the file. Audiobook files can be
huge, hard to navigate.

Thanks for SMP

**Comment by souch** [comment]
Mm, why not, 
I wanted to make the play pause bigger in big font mode only. I like the play at the left, sorry :-) 
Also you can fork SMP, the modification you ask can be made from XML file almost without any knowledge of Java programming.
Save the time of the last song is easy but I don't have a lots of time right now so don't expects anything fast. Also I need to see how others do to make the app themable.

**Comment by souch** [comment]
I added remember last location in commit a1c775fb426964fb22d1a7ca59520f1cc6f2f5b4 . It is disabled by default in the settings as it is not useful for me.

Also to make you feel less bored I added also a turning disc when the music is playing :-). I hope people will not be annoyed by that.

Don't know if I will take time to make the app themable.

**Comment by souch** [comment]
For fun I'd like to make the disc turn following the current music beat. Seems not easy to make it simple and light for the CPU.

**Comment by goldencut** [comment]
Wow, that's fast. Version with new features coming to F-Droid too? Would like to see what that turning disc looks like. Btw, if changing the basic 2 colors is as easy as changing 2 values in XML then maybe add these values to settings section so user can input them? I think nobody really minds using color selector/picker app to get RGB or HTML color codes and entering them manually. Well, I wouldn't..

**Comment by souch** [comment]
Yes, I am currently in a development hurry period!
The update is available on f-droid since yesterday.

The buttons are png images, so no, you can't change them just by changing a XML values, you have to change the color of each picture. 
But font and background color can be changed from XML.

I did not dig on the subject, but I think to make a themable app it should be better to add a folder in the settings where we try to load pictures, fonts, color.
Anyway, I don't think a lot of people use my app so I don't think theme is necessary for the moment.
You can try by yourself using studio or eclipse and an image editor (gimp inkscape) to change the theme.

Anyway

**Comment by goldencut** [comment]
My bad - F-Droid wasn't up to date on my device so I didn't see it. The new version is very nice, that small change - remember last track time - makes IMHO huge difference in usability. 
I actually don't like bitmap themed apps too much, reason being what you already mentioned - for every little change a different set of bitmaps is needed; buttons made with bitmaps would be as far as I would go, at least that's the approach most audio players I like take (1by1, Quod Libet, Audacious, DeaDBeeF, XMPlay being an exception). There might also be alternative path for buttons and color configurations - https://google.github.io/material-design-icons/ I'm no programmer, at all, but I'll try to take a look at the source.

**Comment by souch** [comment]
I am glad that you like it. :-) . I'll have a look someday to the theme problematic. I am not sure the github repos you point out could answer this issue.

**Comment by goldencut** [comment]
Eh, my bad... What I was trying to convey was the idea of using (freeware) FONT for buttons ie include some freeware font (or self-made) that has the required prev, next, play and other characters (like Webdings font in Windows). So the player button has a single character on it (of that font), which scales, can even maybe be bold, italic etc. With fonts I suspect it would be quite easy to change colors, and no more (duplicate) bitmap images. Just to explain the idea..
PS. I noticed some audio players put prev-pause-next buttons in the notification area (like Clean player for example) - quite handy.

Thanks & keep up the good work

**Comment by souch** [comment]
I don't know, I still don't see what the purpose of this, send me a pull request :-)

**Comment by goldencut** [comment]
Yeah, I should learn some programming not flood other people with my "great ideas" about their software... :P Anyway, the idea was that instead of bitmaps as buttons you could use text-based buttons: imagine every one of those red playback buttons being not a bitmap but a simple Unicode character (for example A B C D E). Now if you use any Unicode (v7 or later) font that already has playback characters (like in Webdings font in MS Windows) you can use that font for playback buttons. Instead of A B C D E you would use some other Unicode characters (http://unicode.org/~asmus/web-wing-ding-ext.pdf, http://www.fileformat.info/info/unicode/char/search.htm). As an example (to try it out), if the operating system you are using is MS Windows you could open Notepad.exe, paste these 7 characters there: 4;78²Ð³ and select them all, now go to 'Format'-menu and choose 'Font...', select Webdings as a font, select 20 as size and press 'OK'. You will see that those weird characters become playback buttons. So for Sicmu, to create color schemes for the player, instead of laborious work of creating different colored bitmaps beforehand you could just use regular Unicode characters for buttons, then set the font color in whole UI and the playback buttons would change colors with the rest of the fonts in the app. Sorry for lengthy and late post but I had to give another shot to making my idea comprehensible... ;)

**Comment by souch** [comment]
Yes, why not, but I have no time to do this and I like that my button are images so that I can put the exact image I want. 
I could get the exact image I want using your solution by creating a special font with my images in it, but like I said, I will see this in the future.
