### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by memetg** [souch/SMP#16]
I'd like to contribute to (or do) the Turkish translation if the app is multilingual.

**Comment by souch** [comment]
Yes it is possible, it has already a serbian translation [here](SMP/app/src/main/res/values-sr/strings.xml), I am not sure this translation is totally up to date.

You perhaps already know but if you want to translate in turquish start from the english original [strings.xml](SMP/app/src/main/res/values/strings.xml) translate it, put it in values-tr/strings.xml and submit a pull request. 

When you translate, please take care of the space the new words takes and that they will not make the SicMu GUI appears strange or awkward.

**Comment by memetg** [comment]
It's done, but there are two problems with the translation. The first one is I'm totally noob when it comes to github. ~~I cannot figure out how to create the folder values-tr to put the file in it. Can you do it  for me? [Link  to the code](http://paste.ofcode.org/qnhqqWnvsqu5VBw7FMipVt).~~ I've figured it out...
The second problem is with a dialogue that will look ugly in Turkish.
The English version says:

```
<string name="settings_unfold_subgroup_threshold">Unfold subgroups if group</string>
<string name="settings_unfold_subgroup_threshold_default">18</string>
<string name="settings_unfold_subgroup_threshold_summary1">has less than</string>
<string name="settings_unfold_subgroup_threshold_summary2">songs</string>
```

and this is read by the application as: 
_**Unfold subgroups if group**
has less than 18 songs._
The title is _"Unfold subgroups if group"_
and the dialogue reads:
_Unfold subgroups if group 18_

The third string comes before the number (i.e., the second string). This will look ugly in Turkish, because I cannot put more than two words before the number "18".  The title will be just one word (which means "if")
_**Eğer**_ 
_altgruplar 18 şarkıdan daha azını içeriyorsa genişlet_
and the dialoge will read
_Eğer 18_

Not totally useless, but ugly.

By the way, just out of curiosity, I suppose you're French, why isn't there a French translation?

**Comment by souch** [comment]
Hi,

great, you managed to create a directory :-) .

the commit e5992e6 merge the 2 lines so that you can put now the %d where you want. I hope it helps.

I started to translate it in french but I prefer seeing it in english on my phone (words are more concise).
As I did initially the app only for myself (I do not know how many people use it, nor how many french) I threw the translation :-) .

**Comment by memetg** [comment]
I don't know how many people use it, but it's a nice app, especially the folder based playing and the ☭ icon :) I have a Blackberry z10 and it works better for me than the stock bb10 music player. 

I've made some updates on the translation including the merged lines, it's now better.

**Comment by souch** [comment]
Yes I like it too :-) .
Next improvement will be to be able to have information on song/album and to be able to delete song file/album/dir from sicmu.

Do you need that I launch a new version on f-droid so that you can get it from there?

**Comment by memetg** [comment]
I'm already happy with the English version, so it's not urgent. I can wait if you have other plans before launching a new release. Time is on your side.

**Comment by souch** [comment]
OK i'll see when I'll do it. Thanks.
