### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by theduskin** [souch/SMP#2]
the fontsize makes it too flimsy. I tried 25-30 for the title-textview, seems ok(for me).
I think a swipe zoom would cause unexpected behavior, maybe bigger/smaller buttons in menu can do the job?

in artist view tabbing the artist should expand only the album level.

please implement  audioeffect/equalizer  as the old stockplayer does.

just my 5ct, as a 1by1 fan I like it already

**Comment by souch** [comment]
Hi, thanks for your interest in my app.

Tuneable fontsize is definitely the next feature I will add. Once done, tell me if it suit your need.

I'll add, to the todolist, a setting that make only the sublevel group unfold. I thought of your feature but didn't know if it would be useful for someone. 
By "tabbing" you mean "tap"?
For folder view, you prefer that the artist group is unfolded too when unfolding the upper folder group?

I'll add audioeffect/equalizer to the todolist, but for me it is a low priority. 

I did not know 1by1, on linux I use Audacious.

**Comment by theduskin** [comment]
tap yes i meant tap.

my folders are organized like this: root/artist/album/track.
the artist view reflects this perfect.
for me it is better to tap a second time than scrolling( especially with larger fontsize) to find a certain song.

> > For folder view, you prefer that the artist group is unfolded too when unfolding the upper folder group?
> > good question, in a soundtrack folder it would be annoying. maybe depending on whether or not sub-folders included()?
> > 
> > I'll add audioeffect/equalizer to the todolist, but for me it is a low priority.
> > kiss, there are enough bloated nonfunctional players out there

another idea: should  comparable call StringUtils.strip("tHe bAnd".toLowerCase(), " "). to catch different notations of artist and album?

**Comment by souch** [comment]
> my folders are organized like this: root/artist/album/track.

So the artist or folder view gives you roughly the same result.

> another idea: should comparable call StringUtils.strip("tHe bAnd".toLowerCase(), " "). to catch different notations of artist and album?

Is it a problem that you encounter? If yes, dump the data sample (artist, album, songs) and the result in the app here. 
I think the current code do already sthg like this : `a.getArtist().compareToIgnoreCase(b.getArtist());` to merge different case of artist. Just a guess from the code, I did not try it. I never saw artist or album name with space around so I don't think strip is necessary.

**Comment by souch** [comment]
Perhaps sthg like this could be even better to catch different notation:
`a.getArtist().replaceAll('[_ -.]', '').compareToIgnoreCase(...);` .
But again, it has to be a problem encountered: I don't want to complexify or slow the app for problems rarely encountered.

**Comment by theduskin** [comment]
yes, it is a user problem, forget it.

**Comment by theduskin** [comment]
the "turned v" is not displayed on my phone. anyway I found it visually difficult to differ the v's.
so i replaced it and played also with colors. I like it, maybe font-sizes and colors could be taken from a json file or something else.  configurable but not bloating.

![screenshot-1424870081727](https://cloud.githubusercontent.com/assets/4677909/6371614/d7bf329a-bcfd-11e4-97ad-bfa1f1c842bc.png)

**Comment by souch** [comment]
Ok, why not, I'll have a look and change the v ^ letter, someday :-) .

**Comment by souch** [comment]
Closed by v0.4
