### ISSUE TITLE
Missing feature: Repeat single album

### ISSUE THREAD

**Issue by hartwork** [souch/SMP#21]
Hi there!

I'm a happy user of SicMu Player for a while now, well done! What I find myself missing again and again is a way to repeat the current album rather than advancing to the next one. Not only would it allow me to stick to that new album I just got my hands on, it would also protect me from jumping from [London grammar - If you wait](https://www.youtube.com/watch?v=SW9W1VMysgg) right into [Nonpoint - Generation Idiot](https://www.youtube.com/watch?v=-x3nrIy9fQk): a complete change of mood.

Any chance that could be added?

Thanks and best, Sebastian

**Comment by souch** [comment]
Hi,

Why not, but I don't see how exactly I can add it to the current GUI. In which mode are you (sort by artist/folder/tree) ? Just to be sure, you want something that loop over and over on the same album/folder ?
Something like a button 'loop on folder/artist' in the menu would be ok ?

Or just erase London grammar and add this [L'ombre sur la mesure](https://www.youtube.com/watch?v=mzbF5G76hNA) :-) .

And thanks, glad to ear a user, I'm not too much active right now on SMP, but I gather every need and will try to apply it someday, hopefully the soonest possible.

**Comment by hartwork** [comment]
Hi!
I believe I was in "Sort by folder" mode: I had not played with modes before you mentioned it afair.
Loop over same folder/album, yes.
I noticed it could be hard to put a button anywhere but if there was an entry ight next to `Shuffle` in settings, it would be easy enough to find and not be limited to an icon, e.g. keep the door open to repeating a single song or a single artist (potentially across albums). I wouldn't mind going to settings for a switch at all.
Nice song, maybe I need to learn French some time :)

**Comment by souch** [comment]
Ok, I'll see what I can do.

**Comment by hartwork** [comment]
Cool, thank you!

**Comment by souch** [comment]
Hi, I am working on it (it is good when people asks me new features, because it makes me dive into SMP again and I implement at the same time some other features :-) ), and I would like some other point of view in "repeat album mode" :
- If the current song finished and it is the last of the album : the player pick the first song of the current album and play it. This sounds obvious.
- but if the next button is pressed: do SMP should choose the first song of the next album or like before it should loop to the beginning of the current album ?

**Comment by hartwork** [comment]
Nice!

Interesting question. The core difference between the two options to me is that one is breaking out of current rules, while the other keeps respecting them. The ability to break out could be a feature when you _intend_ to break out, and an annoyance, when you didn't intend to.
Let's consider two scenarios: (a) The users picks repeat-album-mode to listen to that every album over and over or (b) the user likes to focus on the same album for a while, and then another album, and then another. Which one is more likely? Also relevant: Is `next` the only action to break out of that very album. (Clear "no", there is touch selection of a specific other song.)
By now it's a clear vote in favour of sticking to the same album with "next" to me: No annoyance, other ways to break out, still supports looping different albums after another. What do you think?

**Comment by souch** [comment]
Mmm, my english is not so fluent, but I think you would prefer that "next" button loop to the same album when in "repeat album mode". Right ? :-)
That's simplier for me to implement.

The same for previous ? (loop to the end of the album if at the beginning)

I think too that's the best solution, because I would like to implement: long tap on "next" will shift to the next album. And will move the currently fast forward feature of the long tap on "next" to another button.

**Comment by hartwork** [comment]
Interesting idea. Sounds very good.

**Comment by souch** [comment]
fixed by 00b278c90be79788ddeed473f8eb435b199fefaa

**Comment by hartwork** [comment]
Very nice, thank you!

I wonder how to best get [the F-Droid package](https://f-droid.org/repository/browse/?fdfilter=sicmu&fdid=souch.smp) updated now: That page doesn't seem to list a maintainer contact.
(When I searched Google Play from my Android 4.x device, SicMu player does not show up in the results (but it seems [to be at 1.0 at Google Play](https://play.google.com/store/apps/details?id=souch.smp&hl=en) still).)

**Comment by souch** [comment]
Yes it seems the update is not started for an unknown reason, I will check that.

**Comment by souch** [comment]
Actually f-droid update is just a bit slow. But I found an annoying bug on < kitkat, so I will wait version 1.1.2 appears on f-droid to push it on google play.

**Comment by souch** [comment]
The 1.1.2 is available on google play.

**Comment by hartwork** [comment]
I finally found it on the device. I needed to search for exactly `souch.smp` to find it. My guess is that `SicMu` is spell-corrected here without an option to bypass. In the browser it's corrected to `music` as well but I do have the option to bypass it...

Now that I did find and install it, I don't find the repeat config. When I click the "Music mode" button, it says "not implemented". Any ideas why? Is that the button to change it? Version says 1.1.2.

**Comment by souch** [comment]
In the bottom menu, do not click on 'Music mode', this is a future feature, click on 'Repeat ...' .

**Comment by hartwork** [comment]
Found it now. I have a tendency to overlook things that stare me right into the eye sometimes.
Repeat group and track work like a charm, many thanks!
I have sent you a small donation through PayPal now so your next coffee is on me :)

**Comment by souch** [comment]
great, thanks !!
