### ISSUE TITLE
available on F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [souch/SMP#22]
Just wondering: The `README.md` writes the app is available on F-Droid – but following the link, F-Droid writes it doesn't know about it. Something missing? Maybe you could attach the `.apk` to the `releases/`, so I could grab it and put it into [my F-Droid compatible repo](https://android.izzysoft.de/repo) to make it come "true in a way" at least? Updates would then usually be available in my repo within 24h of your attaching them there (with a new tag/release, of course).

**Comment by souch** [comment]
Yep, I don't know why the sicmu f-droid's page disappeared. I'll ask them.

**Comment by souch** [comment]
Anyway, the build do still work, so you can download the apk from f-droid app and do whatever you want with it. Once the 1.1.2 will be built I will put it on google play too.

**Comment by IzzySoft** [comment]
That's strange. When I use the F-Droid client, I find it. But when I query the index, it's not there. Hm. OK, so my offer is there and *might* be obsolete – but be welcome to take me on it anyway :wink:

**Comment by souch** [comment]
SicMu player [page](https://f-droid.org/repository/browse/?fdfilter=smp&fdid=souch.smp) reappeared with the new release. I added the new release to google play too.

**Comment by souch** [comment]
F-droid issue [here](https://gitlab.com/fdroid/rfp/issues/214)
