### ISSUE TITLE
Feature Request: Make "shuffle" option easier to reach

### ISSUE THREAD

**Issue by TaoK** [souch/SMP#28]
I often ask my music player to play something random (across my whole collection, or across a genre), and skip from random song to random song until I find something I want to listen to at that moment. Then I typically disable shuffle (and maybe go back to the first song in the album).

SicMu makes this slightly harder than I feel it should ideally be, because it treats shuffle as a "Setting" on the separate settings page (that you then need to back out of, after having changed your selection).
I'm not sure what the best approach is to fixing this... Maybe adding a third row of quick settings on the quick popup in the corner?

**Comment by souch** [comment]
I think there can be only two row. I'll see what I can do, as I wanted to keep one button for the new mode (edit mode). But you're right, shuffle should not be in the settings.
