### ISSUE TITLE
Anecdotal: Android battery usage tracking claims SicMu is using a lot of battery

### ISSUE THREAD

**Issue by TaoK** [souch/SMP#30]
This morning I decided to look at my battery usage after a few hours (new phone, new usage patterns, lots of new apps), and was very surprised to see SicMu at the top of my battery usage list, even though I at no point opened it in the 4 hours since my last full charge.

At first I thought "hmm, I enabled the possibly-non-standard media key support, maybe that's it" but looking at the manifest xml and the media intent receiver class I don't see anything clearly wrong... the only explanation there would be if my phone were getting/sending a constant stream of media intents due to some hardware flaw...?

So, no clear issue report yet, sorry, but possibly something concerning there. I'll try to check again tomorrow.

**Comment by souch** [comment]
I never had this issue. Right now SMP is in background (not destroyed) and after 7 hours without charging SMP does not show up in the usage list (the least in the usage list in 1%).

**Comment by TaoK** [comment]
I have been unable to reproduce. Don't know what happened. As far as I'm concerned this can be closed, sorry about the false alarm.
