### ISSUE TITLE
Media Pause does not update notification area when SicMu is in background, shows as still playing

### ISSUE THREAD

**Issue by TaoK** [souch/SMP#31]
Normal / as expected:

* When SicMu is in the foreground, there is no Notification, so this comment/concern does not apply.
* When SicMu starts playing __while in the background__, a notification area entry correctly appears listing the track being played.
* When SicMu moves into the background (due to the user pressing the home button, for example) a notification area entry correctly appears listing the track being played, __if a track is playing__.
* When SicMu, while in the background, starts playing a new track (due to user clicking the "next track" media button or the current track completing) the notification area entry correctly updates to the new track being played.

Unexpected:

* When SicMu, while in the background, __stops__ playing a track (because the user pauses, using a media button, or unplugs earphones), the notification area is not updated; it keeps saying "SicMu playing [some track]", and the record icon keeps rotating.

I'm using a Nokia 8 running Android 8.0.0 with bluetooth headphones, but I suspect the specifics don't matter - I've just checked with wired headphones, and the same thing happens. I'm using SicMu v1.2.

**Comment by souch** [comment]
Yes have this bug too, it is here since the beginning of the notification I think. I'll fix it when I'll have time.
