### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by mayowadavid** [souch/SMP#38]
Hello,
I came across your amazing music player then i decided to make a cool logo that will help communicate the name of the application and at the same time show that it is a music application, if you like it you can use it on your application
Cheers!
Here is a link to all the original files
https://drive.google.com/folderview?id=1WpdCtm29juHS2Hwkh50M6WO-0iqpiHbw

![DIFFERENT ICON STYLE.png](https://steemitimages.com/DQmSe77bkZdArQoLpC3kf7NviRFn4fasWhzxJFn3APKXRab/DIFFERENT%20ICON%20STYLE.png)

![DIFFERENT COLOURS.png](https://steemitimages.com/DQmTkEJ8MbSgYLLUPQgbvwa6CbHzFNqtHHwTM3Xitr7QCDa/DIFFERENT%20COLOURS.png)

**Comment by souch** [comment]
Yep why not, but you know SM in french means sadomasochism, even I have nothing against it, I prefer my logo, sorry. Moreover the app name abbreviation is more SMP than SM.

**Comment by mayowadavid** [comment]
Ok

**Comment by anaufalm** [comment]
Can I make a new one for you? I have the idea for this. :) @souch

**Comment by souch** [comment]
Like you want. I don't understand why so many people want to change the logo. In my opinion, it is the least important improvement needed by Sicmu player.

**Comment by anaufalm** [comment]
You know I dont have basic on coding. I just make a design, this is what I can contribute :D
