### ISSUE TITLE
Feature request: add support for headphones button (pause, unpause, skip)

### ISSUE THREAD

**Issue by Vrihub** [souch/SMP#4]
Very nice app! It would be good to have support for the headphones button, like in the standard music player: short press pauses/unpauses, long press skips to next track

**Comment by souch** [comment]
Thanks! I'll have a look, I don't have a device with that kind of button. Which device has this kind of button?

**Comment by souch** [comment]
Fortunately someone gave me a bluetooth headphone, so I could implement this feature. But I couldn't test the 'long press skips to next track' as I don't think my headphone has a KEYCODE_HEADSETHOOK button. 
Could you confirm 'long press skips to next track' works allright?
