### ISSUE TITLE
Vibration on touch not working in SicMu Player

### ISSUE THREAD

**Issue by adisalat2** [souch/SMP#43]
Project Information
-Repository
https://github.com/souch/SMP

-Project Name: SicMu player

Expected Behaviour
Vibrate on touch should be working when enable under application setting

Actual Behaviour
Application was unable to vibrate on touch after enabling it under app setting

How to reproduce
Download the app from Fdroid
Start the app
Go to settings
Select Advanced setting
Scroll onto vibrate on touch option,then enable it.
Touch any button in the app.
Hence the bug 

Recording of the bug

https://youtu.be/pEaDm8KRz4w

**Comment by souch** [comment]
That's strange, i don't think there is a bug here. And I see that all your contributions to others projects are of that kinds. You open similar issues with other account too (e.g. pzdawood). I don't know your purpose, but I am not sure you've got good intentions. I should report it to github.
