### ISSUE TITLE
SicMu player app crashes when I put the value of unfold subgroup if group and Click on ok botton. 

### ISSUE THREAD

**Issue by pzdawood** [souch/SMP#44]
### Actual behaviour
When I open the sicMub player  app and open the settings of the app . After that I open the advanced settings option . Then I click on unfold subgroup if group and put the value and click on ok botton app suddenly crashes. Then I reopen the app and  I click on settings option app suddenly crashes. Settings will not open till I uninstall this app and install this app again.
### How to reproduce
* Download the sicMu player app from F-driod.
* Install this app.
* Open the sicMu player app. 
* Choose settings option of the app.
* Click on advanced settings option.
* After that open the  unfold subgroup if group option and put value .
* Then click on ok botton app suddenly crashes.
* Reopen the app and Click on settings option app suddenly crashes.
* Browser: sicMu player.
* Version: 1.3
* Operating system:7.1.2
### Recording of the bug
https://youtu.be/vmXqvQm7CTQ

**Comment by souch** [comment]
That's strange, i don't think there is a bug here. And I see that all your contributions to others projects are of that kinds. You open similar issues with other account too (e.g. adisalat2). I don't know your purpose, but I am not sure you've got good intentions. I should report it to github.
