### ISSUE TITLE
lock button not working properly

### ISSUE THREAD

**Issue by kr-nahid** [souch/SMP#45]
#### Expected behavior
user should be  able to lock screen when click on lock icon

#### Actual behavior
when i click on lock nothing happen . its cant able to lock screen .

#### How to reproduce
* download the app
* open it
* then click on lock
* and note the bug

> Browser/App version: SicMu Player v1.3 
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=if4MqJ-_4Ao

**Comment by souch** [comment]
That's strange, i don't think there is a bug here. And I  see that all your contributions to others projects are of that kinds.  You open similar issues with other account too (e.g. pzdawood). I don't  know your purpose, but I am not sure you've got good intentions. I  should report it to github.
