### ISSUE TITLE
Long press on prev/next icons doesn't seek back/forward

### ISSUE THREAD

**Issue by Vrihub** [souch/SMP#5]
I don't know if this is a feature not implemented, or a bug on my old android 2.3 device: I would expect that a long press on the "prev" and "next" icons would seek backwards or forward in the current track (like in the standard music player). This doesn't happen: the player skips to previous/next track instead.

**Comment by souch** [comment]
No, that just not implemented. It's useless for me, when I start playing a song I listen the whole song. But I will do it someday, it is not too complex to implement.

**Comment by souch** [comment]
The implementation is a bit less smooth than android's original music player. I hope it will be good enough for you.
