### ISSUE TITLE
Feature request: please add "folder tree" view

### ISSUE THREAD

**Issue by Vrihub** [souch/SMP#6]
Some people (like me :) ) use to organise their audio files in a folder tree/hierarchy, for example I use the first level of the tree for main categories (music, podcasts, work/teaching stuff, etc), the second level for the "author" (artist, or podcast author etc), the third level for "album" (or similar) and so on.

Now, nearly all android music players (including SMP) provide a "by folder" view, but this is a flattened list of all folders and subfolders, where the nesting/level/tree information is lost, so navigating to the desired folder is quite cumbersome, when you have hundreds of folders.

I would like to have a "folder tree" view, where I can quickly navigate from the root folder to the desired subfolder; by "tree" I don't mean it should graphically appear as a tree: it should appear as a list of folders, starting from the (user defined) root folder, just like the current "by folder" view of SMP;  clicking on each folder should present a list of its subfolders and so on, just like in traditional file managers.

**Comment by souch** [comment]
I thought about that, but I thought people usually don't have too many songs on their devices. Seems to be wrong. 
This feature is a bit complex to implement, but I think it's cool. I'll do it as soon as possible.

**Comment by Vrihub** [comment]
On Fri, Mar 06, 2015 at 01:23:06PM -0800, souch wrote:

>    I thought about that, but I thought people usually don't have too many
>    songs on their devices. Seems to be wrong.
>    This feature is a bit complex to implement, but I think it's cool. I'll do
>    it as soon as possible.

Hi, I'm so happy this feature has been implemented. Thank you very much!!!

Cri

**Comment by souch** [comment]
Thanks a lot for your enthusiasm ! 

I am a bit disappointed by how the tree look like, I'll perhaps try to improve a bit the listview to show a bit better the tree hierarchy. But I have not really good idea how to do it nice and compact.
